
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.HBox hbox1;
	private global::Gtk.VBox vbox2;
	private global::Gtk.Label label1;
	private global::Gtk.HBox hbox2;
	private global::Gtk.Label label2;
	private global::Gtk.Entry entry4;
	private global::Gtk.HBox hbox4;
	private global::Gtk.VBox vbox3;
	private global::Gtk.Label label4;
	private global::Gtk.Button button1;
	private global::Gtk.Fixed fixed8;
	private global::Gtk.VBox vbox4;
	private global::Gtk.Label label3;
	private global::Gtk.ComboBox combobox1;
	private global::Gtk.Notebook notebook2;
	private global::Gtk.Notebook notebook3;
	private global::Gtk.Notebook notebook4;
	private global::Gtk.Fixed fixed2;
	private global::Gtk.Entry entry1;
	private global::Gtk.Label label17;
	private global::Gtk.Label label18;
	private global::Gtk.Entry entry2;
	private global::Gtk.Label label19;
	private global::Gtk.ComboBox combobox2;
	private global::Gtk.ComboBox combobox8;
	private global::Gtk.Label label20;
	private global::Gtk.Button button2;
	private global::Gtk.Label label15;
	private global::Gtk.Label label7;
	private global::Gtk.Label label5;
	private global::Gtk.Label label6;
	private global::Gtk.Label label8;
	private global::Gtk.Label label9;
	private global::Gtk.Fixed fixed5;
	private global::Gtk.Label label10;
	private global::Gtk.Label label11;
	private global::Gtk.Label label12;
	private global::Gtk.Entry entry3;
	private global::Gtk.ComboBox combobox3;
	private global::Gtk.ComboBox combobox4;
	private global::Gtk.ComboBox combobox5;
	private global::Gtk.ComboBox combobox6;
	private global::Gtk.ComboBox combobox7;
	private global::Gtk.Button button4;
	private global::Gtk.Label label13;
	private global::Gtk.CheckButton checkbutton4;
	private global::Gtk.CheckButton checkbutton5;
	private global::Gtk.Label label14;
	private global::Gtk.Table table5;
	private global::Gtk.Fixed fixed7;
	private global::Gtk.Fixed fixed9;
	private global::Gtk.Table table2;
	private global::Gtk.Entry entry5;
	private global::Gtk.Label label21;
	private global::Gtk.Label label22;
	private global::Gtk.Label label23;
	private global::Gtk.Label label24;
	private global::Gtk.Label label25;
	private global::Gtk.Label label26;
	private global::Gtk.Label label27;
	private global::Gtk.Label label28;
	private global::Gtk.Label label29;
	private global::Gtk.Label label30;
	private global::Gtk.Label label31;
	private global::Gtk.Table table7;
	private global::Gtk.Button button3;
	private global::Gtk.Label label32;
	private global::Gtk.Label label16;
	private global::Gtk.Fixed fixed3;
	private global::Gtk.Label label34;
	private global::Gtk.Label label35;
	private global::Gtk.Label label36;
	private global::Gtk.Label label37;
	private global::Gtk.Label label38;
	private global::Gtk.Label label39;
	private global::Gtk.Label label40;
	private global::Gtk.Label label41;
	private global::Gtk.Label label42;
	private global::Gtk.Label label43;
	private global::Gtk.Entry entry6;
	private global::Gtk.ComboBox combobox9;
	private global::Gtk.Label label45;
	private global::Gtk.Label label44;
	private global::Gtk.Button button5;
	private global::Gtk.Label label33;
	private global::Gtk.HBox hbox3;
	private global::Gtk.Fixed fixed4;
	private global::Gtk.Label label47;
	private global::Gtk.Entry entry7;
	private global::Gtk.Label label48;
	private global::Gtk.Label label49;
	private global::Gtk.Label label50;
	private global::Gtk.Label label51;
	private global::Gtk.Label label52;
	private global::Gtk.Label label53;
	private global::Gtk.Label label54;
	private global::Gtk.Label label55;
	private global::Gtk.Label label56;
	private global::Gtk.Label label57;
	private global::Gtk.Label label58;
	private global::Gtk.Label label59;
	private global::Gtk.VBox vbox5;
	private global::Gtk.HBox hbox5;
	private global::Gtk.CheckButton checkbutton7;
	private global::Gtk.CheckButton checkbutton8;
	private global::Gtk.HBox hbox6;
	private global::Gtk.VBox vbox6;
	private global::Gtk.ComboBox combobox10;
	private global::Gtk.ComboBox combobox12;
	private global::Gtk.VBox vbox7;
	private global::Gtk.ComboBox combobox11;
	private global::Gtk.ComboBox combobox13;
	private global::Gtk.ComboBox combobox14;
	private global::Gtk.VBox vbox8;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TreeView treeview1;
	private global::Gtk.HBox hbox7;
	private global::Gtk.HBox hbox8;
	private global::Gtk.Button button7;
	private global::Gtk.Button button8;
	private global::Gtk.Button button6;
	private global::Gtk.Button button12;
	private global::Gtk.Label label46;
	private global::Gtk.HBox hbox9;
	private global::Gtk.Fixed fixed6;
	private global::Gtk.Label label60;
	private global::Gtk.Entry entry8;
	private global::Gtk.Label label62;
	private global::Gtk.Label label63;
	private global::Gtk.Label label64;
	private global::Gtk.Label label65;
	private global::Gtk.Label label66;
	private global::Gtk.Label label67;
	private global::Gtk.Label label68;
	private global::Gtk.Label label69;
	private global::Gtk.Label label70;
	private global::Gtk.Label label71;
	private global::Gtk.Label label72;
	private global::Gtk.Label label73;
	private global::Gtk.VBox vbox9;
	private global::Gtk.HBox hbox10;
	private global::Gtk.CheckButton checkbutton9;
	private global::Gtk.CheckButton checkbutton10;
	private global::Gtk.HBox hbox11;
	private global::Gtk.VBox vbox10;
	private global::Gtk.ComboBox combobox15;
	private global::Gtk.ComboBox combobox16;
	private global::Gtk.VBox vbox11;
	private global::Gtk.ComboBox combobox17;
	private global::Gtk.ComboBox combobox18;
	private global::Gtk.ComboBox combobox19;
	private global::Gtk.VBox vbox12;
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	private global::Gtk.TreeView treeview2;
	private global::Gtk.HBox hbox12;
	private global::Gtk.HBox hbox13;
	private global::Gtk.Button button9;
	private global::Gtk.Button button10;
	private global::Gtk.Button button11;
	private global::Gtk.Label label61;
	private global::Gtk.Table table3;
	private global::Gtk.Fixed fixed11;
	private global::Gtk.Fixed fixed12;
	private global::Gtk.ScrolledWindow GtkScrolledWindow2;
	private global::Gtk.TreeView treeview3;
	private global::Gtk.VBox vbox13;
	private global::Gtk.Table table4;
	private global::Gtk.Entry entry9;
	private global::Gtk.Label label74;
	private global::Gtk.Label label75;
	private global::Gtk.Label label77;
	private global::Gtk.Label label79;
	private global::Gtk.Label label80;
	private global::Gtk.Table table6;
	private global::Gtk.Button button13;
	private global::Gtk.Button button14;
	private global::Gtk.HBox hbox14;
	private global::Gtk.Label label78;
	private global::Gtk.ComboBox combobox20;
	private global::Gtk.Label label81;
	private global::Gtk.ComboBox combobox21;
	private global::Gtk.Label label76;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.WidthRequest = 750;
		this.HeightRequest = 350;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("JobApp - Login");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		this.AllowGrow = false;
		this.DefaultWidth = 750;
		this.DefaultHeight = 350;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.Xalign = 1F;
		this.label1.Justify = ((global::Gtk.Justification)(1));
		this.vbox2.Add (this.label1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Login");
		this.hbox2.Add (this.label2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label2]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.entry4 = new global::Gtk.Entry ();
		this.entry4.CanFocus = true;
		this.entry4.Name = "entry4";
		this.entry4.IsEditable = true;
		this.entry4.InvisibleChar = '•';
		this.hbox2.Add (this.entry4);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.entry4]));
		w3.Position = 1;
		this.vbox2.Add (this.hbox2);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		this.hbox1.Add (this.vbox2);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox2]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.vbox3.Add (this.label4);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label4]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button ();
		this.button1.Sensitive = false;
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("logout");
		this.vbox3.Add (this.button1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.button1]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		this.hbox4.Add (this.vbox3);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox3]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.fixed8 = new global::Gtk.Fixed ();
		this.fixed8.Name = "fixed8";
		this.fixed8.HasWindow = false;
		this.hbox4.Add (this.fixed8);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.fixed8]));
		w9.Position = 1;
		this.hbox1.Add (this.hbox4);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.hbox4]));
		w10.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.Xalign = 0F;
		this.vbox4.Add (this.label3);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.label3]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.combobox1 = global::Gtk.ComboBox.NewText ();
		this.combobox1.Sensitive = false;
		this.combobox1.Name = "combobox1";
		this.vbox4.Add (this.combobox1);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.combobox1]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		this.hbox1.Add (this.vbox4);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox4]));
		w13.Position = 2;
		w13.Expand = false;
		w13.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w14.Position = 0;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.notebook2 = new global::Gtk.Notebook ();
		this.notebook2.CanFocus = true;
		this.notebook2.Name = "notebook2";
		this.notebook2.CurrentPage = 2;
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.notebook3 = new global::Gtk.Notebook ();
		this.notebook3.CanFocus = true;
		this.notebook3.Name = "notebook3";
		this.notebook3.CurrentPage = 0;
		// Container child notebook3.Gtk.Notebook+NotebookChild
		this.notebook4 = new global::Gtk.Notebook ();
		this.notebook4.CanFocus = true;
		this.notebook4.Name = "notebook4";
		this.notebook4.CurrentPage = 0;
		// Container child notebook4.Gtk.Notebook+NotebookChild
		this.fixed2 = new global::Gtk.Fixed ();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry1 = new global::Gtk.Entry ();
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.IsEditable = true;
		this.entry1.InvisibleChar = '•';
		this.fixed2.Add (this.entry1);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.entry1]));
		w15.X = 105;
		w15.Y = 7;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label17 = new global::Gtk.Label ();
		this.label17.Name = "label17";
		this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("User Name");
		this.fixed2.Add (this.label17);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label17]));
		w16.X = 7;
		w16.Y = 10;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label18 = new global::Gtk.Label ();
		this.label18.Name = "label18";
		this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("User Login");
		this.fixed2.Add (this.label18);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label18]));
		w17.X = 7;
		w17.Y = 40;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.entry2 = new global::Gtk.Entry ();
		this.entry2.Sensitive = false;
		this.entry2.CanFocus = true;
		this.entry2.Name = "entry2";
		this.entry2.IsEditable = true;
		this.entry2.InvisibleChar = '•';
		this.fixed2.Add (this.entry2);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.entry2]));
		w18.X = 105;
		w18.Y = 37;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label19 = new global::Gtk.Label ();
		this.label19.Name = "label19";
		this.label19.LabelProp = global::Mono.Unix.Catalog.GetString ("Initial Line");
		this.fixed2.Add (this.label19);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label19]));
		w19.X = 7;
		w19.Y = 73;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.combobox2 = global::Gtk.ComboBox.NewText ();
		this.combobox2.Sensitive = false;
		this.combobox2.Name = "combobox2";
		this.fixed2.Add (this.combobox2);
		global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.combobox2]));
		w20.X = 105;
		w20.Y = 67;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.combobox8 = global::Gtk.ComboBox.NewText ();
		this.combobox8.Sensitive = false;
		this.combobox8.Name = "combobox8";
		this.fixed2.Add (this.combobox8);
		global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.combobox8]));
		w21.X = 105;
		w21.Y = 101;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label20 = new global::Gtk.Label ();
		this.label20.Name = "label20";
		this.label20.LabelProp = global::Mono.Unix.Catalog.GetString ("Initial Role");
		this.fixed2.Add (this.label20);
		global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label20]));
		w22.X = 7;
		w22.Y = 106;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.button2 = new global::Gtk.Button ();
		this.button2.Sensitive = false;
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString ("Commit User");
		this.fixed2.Add (this.button2);
		global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.button2]));
		w23.X = 7;
		w23.Y = 134;
		this.notebook4.Add (this.fixed2);
		// Notebook tab
		this.label15 = new global::Gtk.Label ();
		this.label15.Name = "label15";
		this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("New User");
		this.notebook4.SetTabLabel (this.fixed2, this.label15);
		this.label15.ShowAll ();
		// Notebook tab
		global::Gtk.Label w25 = new global::Gtk.Label ();
		w25.Visible = true;
		this.notebook4.Add (w25);
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Existing User");
		this.notebook4.SetTabLabel (w25, this.label7);
		this.label7.ShowAll ();
		this.notebook3.Add (this.notebook4);
		// Notebook tab
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Users");
		this.notebook3.SetTabLabel (this.notebook4, this.label5);
		this.label5.ShowAll ();
		// Notebook tab
		global::Gtk.Label w27 = new global::Gtk.Label ();
		w27.Visible = true;
		this.notebook3.Add (w27);
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Models");
		this.notebook3.SetTabLabel (w27, this.label6);
		this.label6.ShowAll ();
		// Notebook tab
		global::Gtk.Label w28 = new global::Gtk.Label ();
		w28.Visible = true;
		this.notebook3.Add (w28);
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Lines");
		this.notebook3.SetTabLabel (w28, this.label8);
		this.label8.ShowAll ();
		this.notebook2.Add (this.notebook3);
		// Notebook tab
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("admin");
		this.notebook2.SetTabLabel (this.notebook3, this.label9);
		this.label9.ShowAll ();
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.fixed5 = new global::Gtk.Fixed ();
		this.fixed5.Name = "fixed5";
		this.fixed5.HasWindow = false;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.label10 = new global::Gtk.Label ();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("imei");
		this.fixed5.Add (this.label10);
		global::Gtk.Fixed.FixedChild w30 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label10]));
		w30.X = 15;
		w30.Y = 12;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.label11 = new global::Gtk.Label ();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("model");
		this.fixed5.Add (this.label11);
		global::Gtk.Fixed.FixedChild w31 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label11]));
		w31.X = 15;
		w31.Y = 47;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.label12 = new global::Gtk.Label ();
		this.label12.Name = "label12";
		this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("line");
		this.fixed5.Add (this.label12);
		global::Gtk.Fixed.FixedChild w32 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label12]));
		w32.X = 15;
		w32.Y = 82;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.entry3 = new global::Gtk.Entry ();
		this.entry3.CanFocus = true;
		this.entry3.Name = "entry3";
		this.entry3.IsEditable = true;
		this.entry3.InvisibleChar = '•';
		this.fixed5.Add (this.entry3);
		global::Gtk.Fixed.FixedChild w33 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.entry3]));
		w33.X = 128;
		w33.Y = 7;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.combobox3 = global::Gtk.ComboBox.NewText ();
		this.combobox3.Sensitive = false;
		this.combobox3.Name = "combobox3";
		this.fixed5.Add (this.combobox3);
		global::Gtk.Fixed.FixedChild w34 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.combobox3]));
		w34.X = 128;
		w34.Y = 42;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.combobox4 = global::Gtk.ComboBox.NewText ();
		this.combobox4.Sensitive = false;
		this.combobox4.Name = "combobox4";
		this.fixed5.Add (this.combobox4);
		global::Gtk.Fixed.FixedChild w35 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.combobox4]));
		w35.X = 128;
		w35.Y = 77;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.combobox5 = global::Gtk.ComboBox.NewText ();
		this.combobox5.Sensitive = false;
		this.combobox5.Name = "combobox5";
		this.fixed5.Add (this.combobox5);
		global::Gtk.Fixed.FixedChild w36 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.combobox5]));
		w36.X = 485;
		w36.Y = 7;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.combobox6 = global::Gtk.ComboBox.NewText ();
		this.combobox6.Sensitive = false;
		this.combobox6.Name = "combobox6";
		this.fixed5.Add (this.combobox6);
		global::Gtk.Fixed.FixedChild w37 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.combobox6]));
		w37.X = 485;
		w37.Y = 42;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.combobox7 = global::Gtk.ComboBox.NewText ();
		this.combobox7.Sensitive = false;
		this.combobox7.Name = "combobox7";
		this.fixed5.Add (this.combobox7);
		global::Gtk.Fixed.FixedChild w38 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.combobox7]));
		w38.X = 485;
		w38.Y = 77;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.button4 = new global::Gtk.Button ();
		this.button4.Sensitive = false;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString ("commit prealert");
		this.fixed5.Add (this.button4);
		global::Gtk.Fixed.FixedChild w39 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.button4]));
		w39.X = 286;
		w39.Y = 143;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.label13 = new global::Gtk.Label ();
		this.label13.Name = "label13";
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("main fault");
		this.fixed5.Add (this.label13);
		global::Gtk.Fixed.FixedChild w40 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label13]));
		w40.X = 371;
		w40.Y = 12;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.checkbutton4 = new global::Gtk.CheckButton ();
		this.checkbutton4.Sensitive = false;
		this.checkbutton4.CanFocus = true;
		this.checkbutton4.Name = "checkbutton4";
		this.checkbutton4.Label = global::Mono.Unix.Catalog.GetString ("secondary fault");
		this.checkbutton4.DrawIndicator = true;
		this.checkbutton4.UseUnderline = true;
		this.checkbutton4.FocusOnClick = false;
		this.fixed5.Add (this.checkbutton4);
		global::Gtk.Fixed.FixedChild w41 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.checkbutton4]));
		w41.X = 348;
		w41.Y = 47;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.checkbutton5 = new global::Gtk.CheckButton ();
		this.checkbutton5.Sensitive = false;
		this.checkbutton5.CanFocus = true;
		this.checkbutton5.Name = "checkbutton5";
		this.checkbutton5.Label = global::Mono.Unix.Catalog.GetString ("tertiary fault");
		this.checkbutton5.DrawIndicator = true;
		this.checkbutton5.UseUnderline = true;
		this.fixed5.Add (this.checkbutton5);
		global::Gtk.Fixed.FixedChild w42 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.checkbutton5]));
		w42.X = 348;
		w42.Y = 82;
		this.notebook2.Add (this.fixed5);
		global::Gtk.Notebook.NotebookChild w43 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.fixed5]));
		w43.Position = 1;
		// Notebook tab
		this.label14 = new global::Gtk.Label ();
		this.label14.Name = "label14";
		this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("prealert");
		this.notebook2.SetTabLabel (this.fixed5, this.label14);
		this.label14.ShowAll ();
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.table5 = new global::Gtk.Table (((uint)(3)), ((uint)(4)), false);
		this.table5.Name = "table5";
		this.table5.RowSpacing = ((uint)(2));
		this.table5.ColumnSpacing = ((uint)(2));
		// Container child table5.Gtk.Table+TableChild
		this.fixed7 = new global::Gtk.Fixed ();
		this.fixed7.WidthRequest = 5;
		this.fixed7.HeightRequest = 5;
		this.fixed7.Name = "fixed7";
		this.fixed7.HasWindow = false;
		this.table5.Add (this.fixed7);
		global::Gtk.Table.TableChild w44 = ((global::Gtk.Table.TableChild)(this.table5 [this.fixed7]));
		w44.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.fixed9 = new global::Gtk.Fixed ();
		this.fixed9.WidthRequest = 5;
		this.fixed9.HeightRequest = 5;
		this.fixed9.Name = "fixed9";
		this.fixed9.HasWindow = false;
		this.table5.Add (this.fixed9);
		global::Gtk.Table.TableChild w45 = ((global::Gtk.Table.TableChild)(this.table5 [this.fixed9]));
		w45.TopAttach = ((uint)(2));
		w45.BottomAttach = ((uint)(3));
		w45.LeftAttach = ((uint)(3));
		w45.RightAttach = ((uint)(4));
		w45.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.table2 = new global::Gtk.Table (((uint)(6)), ((uint)(2)), false);
		this.table2.WidthRequest = 315;
		this.table2.Name = "table2";
		this.table2.RowSpacing = ((uint)(6));
		this.table2.ColumnSpacing = ((uint)(6));
		// Container child table2.Gtk.Table+TableChild
		this.entry5 = new global::Gtk.Entry ();
		this.entry5.WidthRequest = 175;
		this.entry5.CanFocus = true;
		this.entry5.Name = "entry5";
		this.entry5.IsEditable = true;
		this.entry5.InvisibleChar = '●';
		this.table2.Add (this.entry5);
		global::Gtk.Table.TableChild w46 = ((global::Gtk.Table.TableChild)(this.table2 [this.entry5]));
		w46.LeftAttach = ((uint)(1));
		w46.RightAttach = ((uint)(2));
		w46.XOptions = ((global::Gtk.AttachOptions)(4));
		w46.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label21 = new global::Gtk.Label ();
		this.label21.WidthRequest = 125;
		this.label21.HeightRequest = 27;
		this.label21.Name = "label21";
		this.label21.Xalign = 0F;
		this.label21.LabelProp = global::Mono.Unix.Catalog.GetString ("imei");
		this.table2.Add (this.label21);
		global::Gtk.Table.TableChild w47 = ((global::Gtk.Table.TableChild)(this.table2 [this.label21]));
		w47.XOptions = ((global::Gtk.AttachOptions)(4));
		w47.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label22 = new global::Gtk.Label ();
		this.label22.HeightRequest = 27;
		this.label22.Name = "label22";
		this.label22.Xalign = 0F;
		this.label22.LabelProp = global::Mono.Unix.Catalog.GetString ("jobid");
		this.table2.Add (this.label22);
		global::Gtk.Table.TableChild w48 = ((global::Gtk.Table.TableChild)(this.table2 [this.label22]));
		w48.TopAttach = ((uint)(1));
		w48.BottomAttach = ((uint)(2));
		w48.XOptions = ((global::Gtk.AttachOptions)(4));
		w48.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label23 = new global::Gtk.Label ();
		this.label23.HeightRequest = 27;
		this.label23.Name = "label23";
		this.label23.Xalign = 0F;
		this.label23.LabelProp = global::Mono.Unix.Catalog.GetString ("model");
		this.table2.Add (this.label23);
		global::Gtk.Table.TableChild w49 = ((global::Gtk.Table.TableChild)(this.table2 [this.label23]));
		w49.TopAttach = ((uint)(2));
		w49.BottomAttach = ((uint)(3));
		w49.XOptions = ((global::Gtk.AttachOptions)(4));
		w49.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label24 = new global::Gtk.Label ();
		this.label24.HeightRequest = 27;
		this.label24.Name = "label24";
		this.label24.Xalign = 0F;
		this.label24.LabelProp = global::Mono.Unix.Catalog.GetString ("manufacturer");
		this.table2.Add (this.label24);
		global::Gtk.Table.TableChild w50 = ((global::Gtk.Table.TableChild)(this.table2 [this.label24]));
		w50.TopAttach = ((uint)(3));
		w50.BottomAttach = ((uint)(4));
		w50.XOptions = ((global::Gtk.AttachOptions)(4));
		w50.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label25 = new global::Gtk.Label ();
		this.label25.HeightRequest = 27;
		this.label25.Name = "label25";
		this.label25.Xalign = 0F;
		this.label25.LabelProp = global::Mono.Unix.Catalog.GetString ("prealerted by");
		this.table2.Add (this.label25);
		global::Gtk.Table.TableChild w51 = ((global::Gtk.Table.TableChild)(this.table2 [this.label25]));
		w51.TopAttach = ((uint)(4));
		w51.BottomAttach = ((uint)(5));
		w51.XOptions = ((global::Gtk.AttachOptions)(4));
		w51.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label26 = new global::Gtk.Label ();
		this.label26.HeightRequest = 27;
		this.label26.Name = "label26";
		this.label26.Xalign = 0F;
		this.label26.LabelProp = global::Mono.Unix.Catalog.GetString ("prealerted at");
		this.table2.Add (this.label26);
		global::Gtk.Table.TableChild w52 = ((global::Gtk.Table.TableChild)(this.table2 [this.label26]));
		w52.TopAttach = ((uint)(5));
		w52.BottomAttach = ((uint)(6));
		w52.XOptions = ((global::Gtk.AttachOptions)(4));
		w52.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label27 = new global::Gtk.Label ();
		this.label27.Name = "label27";
		this.table2.Add (this.label27);
		global::Gtk.Table.TableChild w53 = ((global::Gtk.Table.TableChild)(this.table2 [this.label27]));
		w53.TopAttach = ((uint)(1));
		w53.BottomAttach = ((uint)(2));
		w53.LeftAttach = ((uint)(1));
		w53.RightAttach = ((uint)(2));
		w53.XOptions = ((global::Gtk.AttachOptions)(4));
		w53.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label28 = new global::Gtk.Label ();
		this.label28.Name = "label28";
		this.table2.Add (this.label28);
		global::Gtk.Table.TableChild w54 = ((global::Gtk.Table.TableChild)(this.table2 [this.label28]));
		w54.TopAttach = ((uint)(2));
		w54.BottomAttach = ((uint)(3));
		w54.LeftAttach = ((uint)(1));
		w54.RightAttach = ((uint)(2));
		w54.XOptions = ((global::Gtk.AttachOptions)(4));
		w54.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label29 = new global::Gtk.Label ();
		this.label29.Name = "label29";
		this.table2.Add (this.label29);
		global::Gtk.Table.TableChild w55 = ((global::Gtk.Table.TableChild)(this.table2 [this.label29]));
		w55.TopAttach = ((uint)(3));
		w55.BottomAttach = ((uint)(4));
		w55.LeftAttach = ((uint)(1));
		w55.RightAttach = ((uint)(2));
		w55.XOptions = ((global::Gtk.AttachOptions)(4));
		w55.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label30 = new global::Gtk.Label ();
		this.label30.Name = "label30";
		this.table2.Add (this.label30);
		global::Gtk.Table.TableChild w56 = ((global::Gtk.Table.TableChild)(this.table2 [this.label30]));
		w56.TopAttach = ((uint)(4));
		w56.BottomAttach = ((uint)(5));
		w56.LeftAttach = ((uint)(1));
		w56.RightAttach = ((uint)(2));
		w56.XOptions = ((global::Gtk.AttachOptions)(4));
		w56.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label31 = new global::Gtk.Label ();
		this.label31.Name = "label31";
		this.table2.Add (this.label31);
		global::Gtk.Table.TableChild w57 = ((global::Gtk.Table.TableChild)(this.table2 [this.label31]));
		w57.TopAttach = ((uint)(5));
		w57.BottomAttach = ((uint)(6));
		w57.LeftAttach = ((uint)(1));
		w57.RightAttach = ((uint)(2));
		w57.XOptions = ((global::Gtk.AttachOptions)(4));
		w57.YOptions = ((global::Gtk.AttachOptions)(4));
		this.table5.Add (this.table2);
		global::Gtk.Table.TableChild w58 = ((global::Gtk.Table.TableChild)(this.table5 [this.table2]));
		w58.TopAttach = ((uint)(1));
		w58.BottomAttach = ((uint)(2));
		w58.LeftAttach = ((uint)(1));
		w58.RightAttach = ((uint)(2));
		w58.XOptions = ((global::Gtk.AttachOptions)(4));
		w58.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.table7 = new global::Gtk.Table (((uint)(6)), ((uint)(2)), false);
		this.table7.WidthRequest = 406;
		this.table7.Name = "table7";
		this.table7.RowSpacing = ((uint)(6));
		this.table7.ColumnSpacing = ((uint)(6));
		// Container child table7.Gtk.Table+TableChild
		this.button3 = new global::Gtk.Button ();
		this.button3.WidthRequest = 70;
		this.button3.Sensitive = false;
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString ("Book in");
		this.table7.Add (this.button3);
		global::Gtk.Table.TableChild w59 = ((global::Gtk.Table.TableChild)(this.table7 [this.button3]));
		w59.XOptions = ((global::Gtk.AttachOptions)(4));
		w59.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table7.Gtk.Table+TableChild
		this.label32 = new global::Gtk.Label ();
		this.label32.Name = "label32";
		this.table7.Add (this.label32);
		global::Gtk.Table.TableChild w60 = ((global::Gtk.Table.TableChild)(this.table7 [this.label32]));
		w60.TopAttach = ((uint)(2));
		w60.BottomAttach = ((uint)(3));
		w60.XOptions = ((global::Gtk.AttachOptions)(4));
		w60.YOptions = ((global::Gtk.AttachOptions)(4));
		this.table5.Add (this.table7);
		global::Gtk.Table.TableChild w61 = ((global::Gtk.Table.TableChild)(this.table5 [this.table7]));
		w61.TopAttach = ((uint)(1));
		w61.BottomAttach = ((uint)(2));
		w61.LeftAttach = ((uint)(2));
		w61.RightAttach = ((uint)(3));
		w61.YOptions = ((global::Gtk.AttachOptions)(4));
		this.notebook2.Add (this.table5);
		global::Gtk.Notebook.NotebookChild w62 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.table5]));
		w62.Position = 2;
		// Notebook tab
		this.label16 = new global::Gtk.Label ();
		this.label16.Name = "label16";
		this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("bookin");
		this.notebook2.SetTabLabel (this.table5, this.label16);
		this.label16.ShowAll ();
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.fixed3 = new global::Gtk.Fixed ();
		this.fixed3.Name = "fixed3";
		this.fixed3.HasWindow = false;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label34 = new global::Gtk.Label ();
		this.label34.Name = "label34";
		this.label34.LabelProp = global::Mono.Unix.Catalog.GetString ("imei");
		this.fixed3.Add (this.label34);
		global::Gtk.Fixed.FixedChild w63 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.label34]));
		w63.X = 15;
		w63.Y = 12;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label35 = new global::Gtk.Label ();
		this.label35.Name = "label35";
		this.label35.LabelProp = global::Mono.Unix.Catalog.GetString ("jobid");
		this.fixed3.Add (this.label35);
		global::Gtk.Fixed.FixedChild w64 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.label35]));
		w64.X = 15;
		w64.Y = 47;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label36 = new global::Gtk.Label ();
		this.label36.Name = "label36";
		this.label36.LabelProp = global::Mono.Unix.Catalog.GetString ("screen fault");
		this.fixed3.Add (this.label36);
		global::Gtk.Fixed.FixedChild w65 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.label36]));
		w65.X = 15;
		w65.Y = 117;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label37 = new global::Gtk.Label ();
		this.label37.Name = "label37";
		this.label37.LabelProp = global::Mono.Unix.Catalog.GetString ("primary fault");
		this.fixed3.Add (this.label37);
		global::Gtk.Fixed.FixedChild w66 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.label37]));
		w66.X = 371;
		w66.Y = 12;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label38 = new global::Gtk.Label ();
		this.label38.Name = "label38";
		this.label38.LabelProp = global::Mono.Unix.Catalog.GetString ("secondary fault");
		this.fixed3.Add (this.label38);
		global::Gtk.Fixed.FixedChild w67 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.label38]));
		w67.X = 371;
		w67.Y = 47;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label39 = new global::Gtk.Label ();
		this.label39.Name = "label39";
		this.label39.LabelProp = global::Mono.Unix.Catalog.GetString ("tertiary fault");
		this.fixed3.Add (this.label39);
		global::Gtk.Fixed.FixedChild w68 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.label39]));
		w68.X = 371;
		w68.Y = 82;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label40 = new global::Gtk.Label ();
		this.label40.Name = "label40";
		this.fixed3.Add (this.label40);
		global::Gtk.Fixed.FixedChild w69 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.label40]));
		w69.X = 128;
		w69.Y = 47;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label41 = new global::Gtk.Label ();
		this.label41.Name = "label41";
		this.fixed3.Add (this.label41);
		global::Gtk.Fixed.FixedChild w70 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.label41]));
		w70.X = 485;
		w70.Y = 15;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label42 = new global::Gtk.Label ();
		this.label42.Name = "label42";
		this.fixed3.Add (this.label42);
		global::Gtk.Fixed.FixedChild w71 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.label42]));
		w71.X = 485;
		w71.Y = 47;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label43 = new global::Gtk.Label ();
		this.label43.Name = "label43";
		this.fixed3.Add (this.label43);
		global::Gtk.Fixed.FixedChild w72 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.label43]));
		w72.X = 485;
		w72.Y = 82;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.entry6 = new global::Gtk.Entry ();
		this.entry6.CanFocus = true;
		this.entry6.Name = "entry6";
		this.entry6.IsEditable = true;
		this.entry6.InvisibleChar = '●';
		this.fixed3.Add (this.entry6);
		global::Gtk.Fixed.FixedChild w73 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.entry6]));
		w73.X = 128;
		w73.Y = 7;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.combobox9 = global::Gtk.ComboBox.NewText ();
		this.combobox9.Sensitive = false;
		this.combobox9.Name = "combobox9";
		this.fixed3.Add (this.combobox9);
		global::Gtk.Fixed.FixedChild w74 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.combobox9]));
		w74.X = 128;
		w74.Y = 117;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label45 = new global::Gtk.Label ();
		this.label45.Name = "label45";
		this.fixed3.Add (this.label45);
		global::Gtk.Fixed.FixedChild w75 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.label45]));
		w75.X = 128;
		w75.Y = 82;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label44 = new global::Gtk.Label ();
		this.label44.Name = "label44";
		this.label44.LabelProp = global::Mono.Unix.Catalog.GetString ("model");
		this.fixed3.Add (this.label44);
		global::Gtk.Fixed.FixedChild w76 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.label44]));
		w76.X = 15;
		w76.Y = 82;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.button5 = new global::Gtk.Button ();
		this.button5.Sensitive = false;
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString ("commit screen");
		this.fixed3.Add (this.button5);
		global::Gtk.Fixed.FixedChild w77 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.button5]));
		w77.X = 15;
		w77.Y = 157;
		this.notebook2.Add (this.fixed3);
		global::Gtk.Notebook.NotebookChild w78 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.fixed3]));
		w78.Position = 3;
		// Notebook tab
		this.label33 = new global::Gtk.Label ();
		this.label33.Name = "label33";
		this.label33.LabelProp = global::Mono.Unix.Catalog.GetString ("screen");
		this.notebook2.SetTabLabel (this.fixed3, this.label33);
		this.label33.ShowAll ();
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.fixed4 = new global::Gtk.Fixed ();
		this.fixed4.WidthRequest = 330;
		this.fixed4.Name = "fixed4";
		this.fixed4.HasWindow = false;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.label47 = new global::Gtk.Label ();
		this.label47.Name = "label47";
		this.label47.LabelProp = global::Mono.Unix.Catalog.GetString ("imei");
		this.fixed4.Add (this.label47);
		global::Gtk.Fixed.FixedChild w79 = ((global::Gtk.Fixed.FixedChild)(this.fixed4 [this.label47]));
		w79.X = 15;
		w79.Y = 12;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.entry7 = new global::Gtk.Entry ();
		this.entry7.CanFocus = true;
		this.entry7.Name = "entry7";
		this.entry7.IsEditable = true;
		this.entry7.InvisibleChar = '●';
		this.fixed4.Add (this.entry7);
		global::Gtk.Fixed.FixedChild w80 = ((global::Gtk.Fixed.FixedChild)(this.fixed4 [this.entry7]));
		w80.X = 128;
		w80.Y = 7;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.label48 = new global::Gtk.Label ();
		this.label48.Name = "label48";
		this.label48.LabelProp = global::Mono.Unix.Catalog.GetString ("jobid");
		this.fixed4.Add (this.label48);
		global::Gtk.Fixed.FixedChild w81 = ((global::Gtk.Fixed.FixedChild)(this.fixed4 [this.label48]));
		w81.X = 15;
		w81.Y = 47;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.label49 = new global::Gtk.Label ();
		this.label49.Name = "label49";
		this.label49.LabelProp = global::Mono.Unix.Catalog.GetString ("model");
		this.fixed4.Add (this.label49);
		global::Gtk.Fixed.FixedChild w82 = ((global::Gtk.Fixed.FixedChild)(this.fixed4 [this.label49]));
		w82.X = 15;
		w82.Y = 82;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.label50 = new global::Gtk.Label ();
		this.label50.Name = "label50";
		this.label50.LabelProp = global::Mono.Unix.Catalog.GetString ("primary fault");
		this.fixed4.Add (this.label50);
		global::Gtk.Fixed.FixedChild w83 = ((global::Gtk.Fixed.FixedChild)(this.fixed4 [this.label50]));
		w83.X = 15;
		w83.Y = 117;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.label51 = new global::Gtk.Label ();
		this.label51.Name = "label51";
		this.label51.LabelProp = global::Mono.Unix.Catalog.GetString ("secondary fault");
		this.fixed4.Add (this.label51);
		global::Gtk.Fixed.FixedChild w84 = ((global::Gtk.Fixed.FixedChild)(this.fixed4 [this.label51]));
		w84.X = 15;
		w84.Y = 152;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.label52 = new global::Gtk.Label ();
		this.label52.Name = "label52";
		this.label52.LabelProp = global::Mono.Unix.Catalog.GetString ("tertiary fault");
		this.fixed4.Add (this.label52);
		global::Gtk.Fixed.FixedChild w85 = ((global::Gtk.Fixed.FixedChild)(this.fixed4 [this.label52]));
		w85.X = 15;
		w85.Y = 187;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.label53 = new global::Gtk.Label ();
		this.label53.Name = "label53";
		this.label53.LabelProp = global::Mono.Unix.Catalog.GetString ("screen fault");
		this.fixed4.Add (this.label53);
		global::Gtk.Fixed.FixedChild w86 = ((global::Gtk.Fixed.FixedChild)(this.fixed4 [this.label53]));
		w86.X = 15;
		w86.Y = 222;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.label54 = new global::Gtk.Label ();
		this.label54.Name = "label54";
		this.fixed4.Add (this.label54);
		global::Gtk.Fixed.FixedChild w87 = ((global::Gtk.Fixed.FixedChild)(this.fixed4 [this.label54]));
		w87.X = 128;
		w87.Y = 47;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.label55 = new global::Gtk.Label ();
		this.label55.Name = "label55";
		this.fixed4.Add (this.label55);
		global::Gtk.Fixed.FixedChild w88 = ((global::Gtk.Fixed.FixedChild)(this.fixed4 [this.label55]));
		w88.X = 128;
		w88.Y = 82;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.label56 = new global::Gtk.Label ();
		this.label56.Name = "label56";
		this.fixed4.Add (this.label56);
		global::Gtk.Fixed.FixedChild w89 = ((global::Gtk.Fixed.FixedChild)(this.fixed4 [this.label56]));
		w89.X = 128;
		w89.Y = 117;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.label57 = new global::Gtk.Label ();
		this.label57.Name = "label57";
		this.fixed4.Add (this.label57);
		global::Gtk.Fixed.FixedChild w90 = ((global::Gtk.Fixed.FixedChild)(this.fixed4 [this.label57]));
		w90.X = 128;
		w90.Y = 152;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.label58 = new global::Gtk.Label ();
		this.label58.Name = "label58";
		this.fixed4.Add (this.label58);
		global::Gtk.Fixed.FixedChild w91 = ((global::Gtk.Fixed.FixedChild)(this.fixed4 [this.label58]));
		w91.X = 128;
		w91.Y = 187;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.label59 = new global::Gtk.Label ();
		this.label59.Name = "label59";
		this.fixed4.Add (this.label59);
		global::Gtk.Fixed.FixedChild w92 = ((global::Gtk.Fixed.FixedChild)(this.fixed4 [this.label59]));
		w92.X = 128;
		w92.Y = 222;
		this.hbox3.Add (this.fixed4);
		global::Gtk.Box.BoxChild w93 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.fixed4]));
		w93.Position = 0;
		w93.Expand = false;
		w93.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.checkbutton7 = new global::Gtk.CheckButton ();
		this.checkbutton7.Sensitive = false;
		this.checkbutton7.CanFocus = true;
		this.checkbutton7.Name = "checkbutton7";
		this.checkbutton7.Label = global::Mono.Unix.Catalog.GetString ("Beyond Economical Repair");
		this.checkbutton7.DrawIndicator = true;
		this.checkbutton7.UseUnderline = true;
		this.hbox5.Add (this.checkbutton7);
		global::Gtk.Box.BoxChild w94 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.checkbutton7]));
		w94.Position = 0;
		// Container child hbox5.Gtk.Box+BoxChild
		this.checkbutton8 = new global::Gtk.CheckButton ();
		this.checkbutton8.Sensitive = false;
		this.checkbutton8.CanFocus = true;
		this.checkbutton8.Name = "checkbutton8";
		this.checkbutton8.Label = global::Mono.Unix.Catalog.GetString ("No Fault Found");
		this.checkbutton8.DrawIndicator = true;
		this.checkbutton8.UseUnderline = true;
		this.hbox5.Add (this.checkbutton8);
		global::Gtk.Box.BoxChild w95 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.checkbutton8]));
		w95.Position = 1;
		this.vbox5.Add (this.hbox5);
		global::Gtk.Box.BoxChild w96 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox5]));
		w96.Position = 0;
		w96.Expand = false;
		w96.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.vbox6 = new global::Gtk.VBox ();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.combobox10 = global::Gtk.ComboBox.NewText ();
		this.combobox10.Sensitive = false;
		this.combobox10.Name = "combobox10";
		this.vbox6.Add (this.combobox10);
		global::Gtk.Box.BoxChild w97 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.combobox10]));
		w97.Position = 0;
		w97.Expand = false;
		w97.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.combobox12 = global::Gtk.ComboBox.NewText ();
		this.combobox12.Sensitive = false;
		this.combobox12.Name = "combobox12";
		this.vbox6.Add (this.combobox12);
		global::Gtk.Box.BoxChild w98 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.combobox12]));
		w98.Position = 1;
		w98.Expand = false;
		w98.Fill = false;
		this.hbox6.Add (this.vbox6);
		global::Gtk.Box.BoxChild w99 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.vbox6]));
		w99.Position = 0;
		w99.Expand = false;
		w99.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.vbox7 = new global::Gtk.VBox ();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.combobox11 = global::Gtk.ComboBox.NewText ();
		this.combobox11.Sensitive = false;
		this.combobox11.Name = "combobox11";
		this.vbox7.Add (this.combobox11);
		global::Gtk.Box.BoxChild w100 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.combobox11]));
		w100.Position = 0;
		w100.Expand = false;
		w100.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.combobox13 = global::Gtk.ComboBox.NewText ();
		this.combobox13.Sensitive = false;
		this.combobox13.Name = "combobox13";
		this.vbox7.Add (this.combobox13);
		global::Gtk.Box.BoxChild w101 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.combobox13]));
		w101.Position = 1;
		w101.Expand = false;
		w101.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.combobox14 = global::Gtk.ComboBox.NewText ();
		this.combobox14.Sensitive = false;
		this.combobox14.Name = "combobox14";
		this.vbox7.Add (this.combobox14);
		global::Gtk.Box.BoxChild w102 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.combobox14]));
		w102.PackType = ((global::Gtk.PackType)(1));
		w102.Position = 2;
		w102.Expand = false;
		w102.Fill = false;
		this.hbox6.Add (this.vbox7);
		global::Gtk.Box.BoxChild w103 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.vbox7]));
		w103.Position = 1;
		w103.Expand = false;
		w103.Fill = false;
		this.vbox5.Add (this.hbox6);
		global::Gtk.Box.BoxChild w104 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox6]));
		w104.Position = 1;
		w104.Expand = false;
		w104.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.vbox8 = new global::Gtk.VBox ();
		this.vbox8.Name = "vbox8";
		this.vbox8.Spacing = 6;
		// Container child vbox8.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.treeview1 = new global::Gtk.TreeView ();
		this.treeview1.CanFocus = true;
		this.treeview1.Name = "treeview1";
		this.GtkScrolledWindow.Add (this.treeview1);
		this.vbox8.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w106 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.GtkScrolledWindow]));
		w106.Position = 0;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox ();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox ();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.button7 = new global::Gtk.Button ();
		this.button7.Sensitive = false;
		this.button7.CanFocus = true;
		this.button7.Name = "button7";
		this.button7.UseUnderline = true;
		this.button7.Label = global::Mono.Unix.Catalog.GetString ("Add Entry");
		this.hbox8.Add (this.button7);
		global::Gtk.Box.BoxChild w107 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.button7]));
		w107.Position = 0;
		w107.Expand = false;
		w107.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.button8 = new global::Gtk.Button ();
		this.button8.Sensitive = false;
		this.button8.CanFocus = true;
		this.button8.Name = "button8";
		this.button8.UseUnderline = true;
		this.button8.Label = global::Mono.Unix.Catalog.GetString ("Remove Entry");
		this.hbox8.Add (this.button8);
		global::Gtk.Box.BoxChild w108 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.button8]));
		w108.Position = 1;
		w108.Expand = false;
		w108.Fill = false;
		this.hbox7.Add (this.hbox8);
		global::Gtk.Box.BoxChild w109 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.hbox8]));
		w109.Position = 0;
		w109.Expand = false;
		w109.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.button6 = new global::Gtk.Button ();
		this.button6.Sensitive = false;
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.button6.Label = global::Mono.Unix.Catalog.GetString ("Commit Repair");
		this.hbox7.Add (this.button6);
		global::Gtk.Box.BoxChild w110 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.button6]));
		w110.Position = 1;
		w110.Expand = false;
		w110.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.button12 = new global::Gtk.Button ();
		this.button12.CanFocus = true;
		this.button12.Name = "button12";
		this.button12.UseUnderline = true;
		this.button12.Label = global::Mono.Unix.Catalog.GetString ("Pass to Debug");
		this.hbox7.Add (this.button12);
		global::Gtk.Box.BoxChild w111 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.button12]));
		w111.PackType = ((global::Gtk.PackType)(1));
		w111.Position = 2;
		w111.Expand = false;
		w111.Fill = false;
		this.vbox8.Add (this.hbox7);
		global::Gtk.Box.BoxChild w112 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox7]));
		w112.Position = 1;
		w112.Expand = false;
		w112.Fill = false;
		this.vbox5.Add (this.vbox8);
		global::Gtk.Box.BoxChild w113 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.vbox8]));
		w113.Position = 2;
		this.hbox3.Add (this.vbox5);
		global::Gtk.Box.BoxChild w114 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbox5]));
		w114.Position = 1;
		this.notebook2.Add (this.hbox3);
		global::Gtk.Notebook.NotebookChild w115 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.hbox3]));
		w115.Position = 4;
		// Notebook tab
		this.label46 = new global::Gtk.Label ();
		this.label46.Name = "label46";
		this.label46.LabelProp = global::Mono.Unix.Catalog.GetString ("repair");
		this.notebook2.SetTabLabel (this.hbox3, this.label46);
		this.label46.ShowAll ();
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.hbox9 = new global::Gtk.HBox ();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.fixed6 = new global::Gtk.Fixed ();
		this.fixed6.WidthRequest = 330;
		this.fixed6.Name = "fixed6";
		this.fixed6.HasWindow = false;
		// Container child fixed6.Gtk.Fixed+FixedChild
		this.label60 = new global::Gtk.Label ();
		this.label60.Name = "label60";
		this.label60.LabelProp = global::Mono.Unix.Catalog.GetString ("imei");
		this.fixed6.Add (this.label60);
		global::Gtk.Fixed.FixedChild w116 = ((global::Gtk.Fixed.FixedChild)(this.fixed6 [this.label60]));
		w116.X = 15;
		w116.Y = 12;
		// Container child fixed6.Gtk.Fixed+FixedChild
		this.entry8 = new global::Gtk.Entry ();
		this.entry8.CanFocus = true;
		this.entry8.Name = "entry8";
		this.entry8.IsEditable = true;
		this.entry8.InvisibleChar = '●';
		this.fixed6.Add (this.entry8);
		global::Gtk.Fixed.FixedChild w117 = ((global::Gtk.Fixed.FixedChild)(this.fixed6 [this.entry8]));
		w117.X = 128;
		w117.Y = 7;
		// Container child fixed6.Gtk.Fixed+FixedChild
		this.label62 = new global::Gtk.Label ();
		this.label62.Name = "label62";
		this.label62.LabelProp = global::Mono.Unix.Catalog.GetString ("jobid");
		this.fixed6.Add (this.label62);
		global::Gtk.Fixed.FixedChild w118 = ((global::Gtk.Fixed.FixedChild)(this.fixed6 [this.label62]));
		w118.X = 15;
		w118.Y = 47;
		// Container child fixed6.Gtk.Fixed+FixedChild
		this.label63 = new global::Gtk.Label ();
		this.label63.Name = "label63";
		this.label63.LabelProp = global::Mono.Unix.Catalog.GetString ("model");
		this.fixed6.Add (this.label63);
		global::Gtk.Fixed.FixedChild w119 = ((global::Gtk.Fixed.FixedChild)(this.fixed6 [this.label63]));
		w119.X = 15;
		w119.Y = 82;
		// Container child fixed6.Gtk.Fixed+FixedChild
		this.label64 = new global::Gtk.Label ();
		this.label64.Name = "label64";
		this.label64.LabelProp = global::Mono.Unix.Catalog.GetString ("primary fault");
		this.fixed6.Add (this.label64);
		global::Gtk.Fixed.FixedChild w120 = ((global::Gtk.Fixed.FixedChild)(this.fixed6 [this.label64]));
		w120.X = 15;
		w120.Y = 117;
		// Container child fixed6.Gtk.Fixed+FixedChild
		this.label65 = new global::Gtk.Label ();
		this.label65.Name = "label65";
		this.label65.LabelProp = global::Mono.Unix.Catalog.GetString ("secondary fault");
		this.fixed6.Add (this.label65);
		global::Gtk.Fixed.FixedChild w121 = ((global::Gtk.Fixed.FixedChild)(this.fixed6 [this.label65]));
		w121.X = 15;
		w121.Y = 152;
		// Container child fixed6.Gtk.Fixed+FixedChild
		this.label66 = new global::Gtk.Label ();
		this.label66.Name = "label66";
		this.label66.LabelProp = global::Mono.Unix.Catalog.GetString ("tertiary fault");
		this.fixed6.Add (this.label66);
		global::Gtk.Fixed.FixedChild w122 = ((global::Gtk.Fixed.FixedChild)(this.fixed6 [this.label66]));
		w122.X = 15;
		w122.Y = 187;
		// Container child fixed6.Gtk.Fixed+FixedChild
		this.label67 = new global::Gtk.Label ();
		this.label67.Name = "label67";
		this.label67.LabelProp = global::Mono.Unix.Catalog.GetString ("screen fault");
		this.fixed6.Add (this.label67);
		global::Gtk.Fixed.FixedChild w123 = ((global::Gtk.Fixed.FixedChild)(this.fixed6 [this.label67]));
		w123.X = 15;
		w123.Y = 222;
		// Container child fixed6.Gtk.Fixed+FixedChild
		this.label68 = new global::Gtk.Label ();
		this.label68.Name = "label68";
		this.fixed6.Add (this.label68);
		global::Gtk.Fixed.FixedChild w124 = ((global::Gtk.Fixed.FixedChild)(this.fixed6 [this.label68]));
		w124.X = 128;
		w124.Y = 47;
		// Container child fixed6.Gtk.Fixed+FixedChild
		this.label69 = new global::Gtk.Label ();
		this.label69.Name = "label69";
		this.fixed6.Add (this.label69);
		global::Gtk.Fixed.FixedChild w125 = ((global::Gtk.Fixed.FixedChild)(this.fixed6 [this.label69]));
		w125.X = 128;
		w125.Y = 82;
		// Container child fixed6.Gtk.Fixed+FixedChild
		this.label70 = new global::Gtk.Label ();
		this.label70.Name = "label70";
		this.fixed6.Add (this.label70);
		global::Gtk.Fixed.FixedChild w126 = ((global::Gtk.Fixed.FixedChild)(this.fixed6 [this.label70]));
		w126.X = 128;
		w126.Y = 117;
		// Container child fixed6.Gtk.Fixed+FixedChild
		this.label71 = new global::Gtk.Label ();
		this.label71.Name = "label71";
		this.fixed6.Add (this.label71);
		global::Gtk.Fixed.FixedChild w127 = ((global::Gtk.Fixed.FixedChild)(this.fixed6 [this.label71]));
		w127.X = 128;
		w127.Y = 152;
		// Container child fixed6.Gtk.Fixed+FixedChild
		this.label72 = new global::Gtk.Label ();
		this.label72.Name = "label72";
		this.fixed6.Add (this.label72);
		global::Gtk.Fixed.FixedChild w128 = ((global::Gtk.Fixed.FixedChild)(this.fixed6 [this.label72]));
		w128.X = 128;
		w128.Y = 187;
		// Container child fixed6.Gtk.Fixed+FixedChild
		this.label73 = new global::Gtk.Label ();
		this.label73.Name = "label73";
		this.fixed6.Add (this.label73);
		global::Gtk.Fixed.FixedChild w129 = ((global::Gtk.Fixed.FixedChild)(this.fixed6 [this.label73]));
		w129.X = 128;
		w129.Y = 222;
		this.hbox9.Add (this.fixed6);
		global::Gtk.Box.BoxChild w130 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.fixed6]));
		w130.Position = 0;
		w130.Expand = false;
		w130.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.vbox9 = new global::Gtk.VBox ();
		this.vbox9.Name = "vbox9";
		this.vbox9.Spacing = 6;
		// Container child vbox9.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox ();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.checkbutton9 = new global::Gtk.CheckButton ();
		this.checkbutton9.Sensitive = false;
		this.checkbutton9.CanFocus = true;
		this.checkbutton9.Name = "checkbutton9";
		this.checkbutton9.Label = global::Mono.Unix.Catalog.GetString ("Beyond Economical Repair");
		this.checkbutton9.DrawIndicator = true;
		this.checkbutton9.UseUnderline = true;
		this.hbox10.Add (this.checkbutton9);
		global::Gtk.Box.BoxChild w131 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.checkbutton9]));
		w131.Position = 0;
		// Container child hbox10.Gtk.Box+BoxChild
		this.checkbutton10 = new global::Gtk.CheckButton ();
		this.checkbutton10.Sensitive = false;
		this.checkbutton10.CanFocus = true;
		this.checkbutton10.Name = "checkbutton10";
		this.checkbutton10.Label = global::Mono.Unix.Catalog.GetString ("No Fault Found");
		this.checkbutton10.DrawIndicator = true;
		this.checkbutton10.UseUnderline = true;
		this.hbox10.Add (this.checkbutton10);
		global::Gtk.Box.BoxChild w132 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.checkbutton10]));
		w132.Position = 1;
		this.vbox9.Add (this.hbox10);
		global::Gtk.Box.BoxChild w133 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.hbox10]));
		w133.Position = 0;
		w133.Expand = false;
		w133.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.hbox11 = new global::Gtk.HBox ();
		this.hbox11.Name = "hbox11";
		this.hbox11.Spacing = 6;
		// Container child hbox11.Gtk.Box+BoxChild
		this.vbox10 = new global::Gtk.VBox ();
		this.vbox10.Name = "vbox10";
		this.vbox10.Spacing = 6;
		// Container child vbox10.Gtk.Box+BoxChild
		this.combobox15 = global::Gtk.ComboBox.NewText ();
		this.combobox15.Sensitive = false;
		this.combobox15.Name = "combobox15";
		this.vbox10.Add (this.combobox15);
		global::Gtk.Box.BoxChild w134 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.combobox15]));
		w134.Position = 0;
		w134.Expand = false;
		w134.Fill = false;
		// Container child vbox10.Gtk.Box+BoxChild
		this.combobox16 = global::Gtk.ComboBox.NewText ();
		this.combobox16.Sensitive = false;
		this.combobox16.Name = "combobox16";
		this.vbox10.Add (this.combobox16);
		global::Gtk.Box.BoxChild w135 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.combobox16]));
		w135.Position = 1;
		w135.Expand = false;
		w135.Fill = false;
		this.hbox11.Add (this.vbox10);
		global::Gtk.Box.BoxChild w136 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.vbox10]));
		w136.Position = 0;
		w136.Expand = false;
		w136.Fill = false;
		// Container child hbox11.Gtk.Box+BoxChild
		this.vbox11 = new global::Gtk.VBox ();
		this.vbox11.Name = "vbox11";
		this.vbox11.Spacing = 6;
		// Container child vbox11.Gtk.Box+BoxChild
		this.combobox17 = global::Gtk.ComboBox.NewText ();
		this.combobox17.Sensitive = false;
		this.combobox17.Name = "combobox17";
		this.vbox11.Add (this.combobox17);
		global::Gtk.Box.BoxChild w137 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.combobox17]));
		w137.Position = 0;
		w137.Expand = false;
		w137.Fill = false;
		// Container child vbox11.Gtk.Box+BoxChild
		this.combobox18 = global::Gtk.ComboBox.NewText ();
		this.combobox18.Sensitive = false;
		this.combobox18.Name = "combobox18";
		this.vbox11.Add (this.combobox18);
		global::Gtk.Box.BoxChild w138 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.combobox18]));
		w138.Position = 1;
		w138.Expand = false;
		w138.Fill = false;
		// Container child vbox11.Gtk.Box+BoxChild
		this.combobox19 = global::Gtk.ComboBox.NewText ();
		this.combobox19.Sensitive = false;
		this.combobox19.Name = "combobox19";
		this.vbox11.Add (this.combobox19);
		global::Gtk.Box.BoxChild w139 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.combobox19]));
		w139.PackType = ((global::Gtk.PackType)(1));
		w139.Position = 2;
		w139.Expand = false;
		w139.Fill = false;
		this.hbox11.Add (this.vbox11);
		global::Gtk.Box.BoxChild w140 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.vbox11]));
		w140.Position = 1;
		w140.Expand = false;
		w140.Fill = false;
		this.vbox9.Add (this.hbox11);
		global::Gtk.Box.BoxChild w141 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.hbox11]));
		w141.Position = 1;
		w141.Expand = false;
		w141.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.vbox12 = new global::Gtk.VBox ();
		this.vbox12.Name = "vbox12";
		this.vbox12.Spacing = 6;
		// Container child vbox12.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.treeview2 = new global::Gtk.TreeView ();
		this.treeview2.CanFocus = true;
		this.treeview2.Name = "treeview2";
		this.GtkScrolledWindow1.Add (this.treeview2);
		this.vbox12.Add (this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w143 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.GtkScrolledWindow1]));
		w143.Position = 0;
		// Container child vbox12.Gtk.Box+BoxChild
		this.hbox12 = new global::Gtk.HBox ();
		this.hbox12.Name = "hbox12";
		this.hbox12.Spacing = 6;
		// Container child hbox12.Gtk.Box+BoxChild
		this.hbox13 = new global::Gtk.HBox ();
		this.hbox13.Name = "hbox13";
		this.hbox13.Spacing = 6;
		// Container child hbox13.Gtk.Box+BoxChild
		this.button9 = new global::Gtk.Button ();
		this.button9.Sensitive = false;
		this.button9.CanFocus = true;
		this.button9.Name = "button9";
		this.button9.UseUnderline = true;
		this.button9.Label = global::Mono.Unix.Catalog.GetString ("Add Entry");
		this.hbox13.Add (this.button9);
		global::Gtk.Box.BoxChild w144 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.button9]));
		w144.Position = 0;
		w144.Expand = false;
		w144.Fill = false;
		// Container child hbox13.Gtk.Box+BoxChild
		this.button10 = new global::Gtk.Button ();
		this.button10.Sensitive = false;
		this.button10.CanFocus = true;
		this.button10.Name = "button10";
		this.button10.UseUnderline = true;
		this.button10.Label = global::Mono.Unix.Catalog.GetString ("Remove Entry");
		this.hbox13.Add (this.button10);
		global::Gtk.Box.BoxChild w145 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.button10]));
		w145.Position = 1;
		w145.Expand = false;
		w145.Fill = false;
		this.hbox12.Add (this.hbox13);
		global::Gtk.Box.BoxChild w146 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.hbox13]));
		w146.Position = 0;
		w146.Expand = false;
		w146.Fill = false;
		// Container child hbox12.Gtk.Box+BoxChild
		this.button11 = new global::Gtk.Button ();
		this.button11.Sensitive = false;
		this.button11.CanFocus = true;
		this.button11.Name = "button11";
		this.button11.UseUnderline = true;
		this.button11.Label = global::Mono.Unix.Catalog.GetString ("Commit Debug");
		this.hbox12.Add (this.button11);
		global::Gtk.Box.BoxChild w147 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.button11]));
		w147.Position = 1;
		w147.Expand = false;
		w147.Fill = false;
		this.vbox12.Add (this.hbox12);
		global::Gtk.Box.BoxChild w148 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.hbox12]));
		w148.Position = 1;
		w148.Expand = false;
		w148.Fill = false;
		this.vbox9.Add (this.vbox12);
		global::Gtk.Box.BoxChild w149 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.vbox12]));
		w149.Position = 2;
		this.hbox9.Add (this.vbox9);
		global::Gtk.Box.BoxChild w150 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.vbox9]));
		w150.Position = 1;
		this.notebook2.Add (this.hbox9);
		global::Gtk.Notebook.NotebookChild w151 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.hbox9]));
		w151.Position = 5;
		// Notebook tab
		this.label61 = new global::Gtk.Label ();
		this.label61.Name = "label61";
		this.label61.LabelProp = global::Mono.Unix.Catalog.GetString ("debug");
		this.notebook2.SetTabLabel (this.hbox9, this.label61);
		this.label61.ShowAll ();
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.table3 = new global::Gtk.Table (((uint)(3)), ((uint)(4)), false);
		this.table3.RowSpacing = ((uint)(2));
		this.table3.ColumnSpacing = ((uint)(2));
		// Container child table3.Gtk.Table+TableChild
		this.fixed11 = new global::Gtk.Fixed ();
		this.fixed11.WidthRequest = 5;
		this.fixed11.HeightRequest = 5;
		this.fixed11.Name = "fixed11";
		this.fixed11.HasWindow = false;
		this.table3.Add (this.fixed11);
		global::Gtk.Table.TableChild w152 = ((global::Gtk.Table.TableChild)(this.table3 [this.fixed11]));
		w152.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.fixed12 = new global::Gtk.Fixed ();
		this.fixed12.WidthRequest = 5;
		this.fixed12.HeightRequest = 5;
		this.fixed12.Name = "fixed12";
		this.fixed12.HasWindow = false;
		this.table3.Add (this.fixed12);
		global::Gtk.Table.TableChild w153 = ((global::Gtk.Table.TableChild)(this.table3 [this.fixed12]));
		w153.TopAttach = ((uint)(2));
		w153.BottomAttach = ((uint)(3));
		w153.LeftAttach = ((uint)(3));
		w153.RightAttach = ((uint)(4));
		w153.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.treeview3 = new global::Gtk.TreeView ();
		this.treeview3.WidthRequest = 406;
		this.treeview3.HeightRequest = 238;
		this.treeview3.CanFocus = true;
		this.treeview3.Name = "treeview3";
		this.GtkScrolledWindow2.Add (this.treeview3);
		this.table3.Add (this.GtkScrolledWindow2);
		global::Gtk.Table.TableChild w155 = ((global::Gtk.Table.TableChild)(this.table3 [this.GtkScrolledWindow2]));
		w155.TopAttach = ((uint)(1));
		w155.BottomAttach = ((uint)(2));
		w155.LeftAttach = ((uint)(2));
		w155.RightAttach = ((uint)(3));
		w155.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.vbox13 = new global::Gtk.VBox ();
		this.vbox13.Name = "vbox13";
		this.vbox13.Spacing = 6;
		// Container child vbox13.Gtk.Box+BoxChild
		this.table4 = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
		this.table4.WidthRequest = 315;
		this.table4.Name = "table4";
		this.table4.RowSpacing = ((uint)(6));
		this.table4.ColumnSpacing = ((uint)(6));
		// Container child table4.Gtk.Table+TableChild
		this.entry9 = new global::Gtk.Entry ();
		this.entry9.WidthRequest = 175;
		this.entry9.CanFocus = true;
		this.entry9.Name = "entry9";
		this.entry9.IsEditable = true;
		this.entry9.InvisibleChar = '•';
		this.table4.Add (this.entry9);
		global::Gtk.Table.TableChild w156 = ((global::Gtk.Table.TableChild)(this.table4 [this.entry9]));
		w156.LeftAttach = ((uint)(1));
		w156.RightAttach = ((uint)(2));
		w156.XOptions = ((global::Gtk.AttachOptions)(4));
		w156.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.label74 = new global::Gtk.Label ();
		this.label74.WidthRequest = 125;
		this.label74.HeightRequest = 27;
		this.label74.Name = "label74";
		this.label74.Xalign = 0F;
		this.label74.LabelProp = global::Mono.Unix.Catalog.GetString ("imei");
		this.table4.Add (this.label74);
		global::Gtk.Table.TableChild w157 = ((global::Gtk.Table.TableChild)(this.table4 [this.label74]));
		w157.XOptions = ((global::Gtk.AttachOptions)(4));
		w157.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.label75 = new global::Gtk.Label ();
		this.label75.HeightRequest = 27;
		this.label75.Name = "label75";
		this.label75.Xalign = 0F;
		this.label75.LabelProp = global::Mono.Unix.Catalog.GetString ("jobid");
		this.table4.Add (this.label75);
		global::Gtk.Table.TableChild w158 = ((global::Gtk.Table.TableChild)(this.table4 [this.label75]));
		w158.TopAttach = ((uint)(1));
		w158.BottomAttach = ((uint)(2));
		w158.XOptions = ((global::Gtk.AttachOptions)(4));
		w158.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.label77 = new global::Gtk.Label ();
		this.label77.HeightRequest = 27;
		this.label77.Name = "label77";
		this.label77.Xalign = 0F;
		this.label77.LabelProp = global::Mono.Unix.Catalog.GetString ("model");
		this.table4.Add (this.label77);
		global::Gtk.Table.TableChild w159 = ((global::Gtk.Table.TableChild)(this.table4 [this.label77]));
		w159.TopAttach = ((uint)(2));
		w159.BottomAttach = ((uint)(3));
		w159.XOptions = ((global::Gtk.AttachOptions)(4));
		w159.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.label79 = new global::Gtk.Label ();
		this.label79.Name = "label79";
		this.label79.Xalign = 0F;
		this.table4.Add (this.label79);
		global::Gtk.Table.TableChild w160 = ((global::Gtk.Table.TableChild)(this.table4 [this.label79]));
		w160.TopAttach = ((uint)(1));
		w160.BottomAttach = ((uint)(2));
		w160.LeftAttach = ((uint)(1));
		w160.RightAttach = ((uint)(2));
		w160.XOptions = ((global::Gtk.AttachOptions)(4));
		w160.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.label80 = new global::Gtk.Label ();
		this.label80.Name = "label80";
		this.label80.Xalign = 0F;
		this.table4.Add (this.label80);
		global::Gtk.Table.TableChild w161 = ((global::Gtk.Table.TableChild)(this.table4 [this.label80]));
		w161.TopAttach = ((uint)(2));
		w161.BottomAttach = ((uint)(3));
		w161.LeftAttach = ((uint)(1));
		w161.RightAttach = ((uint)(2));
		w161.XOptions = ((global::Gtk.AttachOptions)(4));
		w161.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox13.Add (this.table4);
		global::Gtk.Box.BoxChild w162 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.table4]));
		w162.Position = 0;
		w162.Expand = false;
		w162.Fill = false;
		// Container child vbox13.Gtk.Box+BoxChild
		this.table6 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
		this.table6.Name = "table6";
		this.table6.RowSpacing = ((uint)(6));
		this.table6.ColumnSpacing = ((uint)(6));
		// Container child table6.Gtk.Table+TableChild
		this.button13 = new global::Gtk.Button ();
		this.button13.WidthRequest = 60;
		this.button13.CanFocus = true;
		this.button13.Name = "button13";
		this.button13.UseUnderline = true;
		this.button13.Label = global::Mono.Unix.Catalog.GetString ("pass");
		this.table6.Add (this.button13);
		global::Gtk.Table.TableChild w163 = ((global::Gtk.Table.TableChild)(this.table6 [this.button13]));
		w163.XOptions = ((global::Gtk.AttachOptions)(4));
		w163.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table6.Gtk.Table+TableChild
		this.button14 = new global::Gtk.Button ();
		this.button14.CanFocus = true;
		this.button14.Name = "button14";
		this.button14.UseUnderline = true;
		this.button14.Label = global::Mono.Unix.Catalog.GetString ("fail");
		this.table6.Add (this.button14);
		global::Gtk.Table.TableChild w164 = ((global::Gtk.Table.TableChild)(this.table6 [this.button14]));
		w164.TopAttach = ((uint)(1));
		w164.BottomAttach = ((uint)(2));
		w164.XOptions = ((global::Gtk.AttachOptions)(4));
		w164.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox13.Add (this.table6);
		global::Gtk.Box.BoxChild w165 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.table6]));
		w165.Position = 1;
		w165.Expand = false;
		w165.Fill = false;
		// Container child vbox13.Gtk.Box+BoxChild
		this.hbox14 = new global::Gtk.HBox ();
		this.hbox14.Name = "hbox14";
		this.hbox14.Spacing = 6;
		// Container child hbox14.Gtk.Box+BoxChild
		this.label78 = new global::Gtk.Label ();
		this.label78.Name = "label78";
		this.label78.LabelProp = global::Mono.Unix.Catalog.GetString ("fail for");
		this.hbox14.Add (this.label78);
		global::Gtk.Box.BoxChild w166 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.label78]));
		w166.Position = 0;
		w166.Expand = false;
		w166.Fill = false;
		// Container child hbox14.Gtk.Box+BoxChild
		this.combobox20 = global::Gtk.ComboBox.NewText ();
		this.combobox20.WidthRequest = 75;
		this.combobox20.Name = "combobox20";
		this.hbox14.Add (this.combobox20);
		global::Gtk.Box.BoxChild w167 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.combobox20]));
		w167.Position = 1;
		w167.Expand = false;
		w167.Fill = false;
		// Container child hbox14.Gtk.Box+BoxChild
		this.label81 = new global::Gtk.Label ();
		this.label81.Name = "label81";
		this.label81.LabelProp = global::Mono.Unix.Catalog.GetString ("fail to");
		this.hbox14.Add (this.label81);
		global::Gtk.Box.BoxChild w168 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.label81]));
		w168.Position = 2;
		w168.Expand = false;
		w168.Fill = false;
		// Container child hbox14.Gtk.Box+BoxChild
		this.combobox21 = global::Gtk.ComboBox.NewText ();
		this.combobox21.WidthRequest = 129;
		this.combobox21.Name = "combobox21";
		this.hbox14.Add (this.combobox21);
		global::Gtk.Box.BoxChild w169 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.combobox21]));
		w169.Position = 3;
		w169.Expand = false;
		w169.Fill = false;
		this.vbox13.Add (this.hbox14);
		global::Gtk.Box.BoxChild w170 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.hbox14]));
		w170.Position = 2;
		w170.Expand = false;
		w170.Fill = false;
		this.table3.Add (this.vbox13);
		global::Gtk.Table.TableChild w171 = ((global::Gtk.Table.TableChild)(this.table3 [this.vbox13]));
		w171.TopAttach = ((uint)(1));
		w171.BottomAttach = ((uint)(2));
		w171.LeftAttach = ((uint)(1));
		w171.RightAttach = ((uint)(2));
		w171.XOptions = ((global::Gtk.AttachOptions)(4));
		w171.YOptions = ((global::Gtk.AttachOptions)(4));
		this.notebook2.Add (this.table3);
		global::Gtk.Notebook.NotebookChild w172 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.table3]));
		w172.Position = 6;
		// Notebook tab
		this.label76 = new global::Gtk.Label ();
		this.label76.Name = "label76";
		this.label76.LabelProp = global::Mono.Unix.Catalog.GetString ("qa");
		this.notebook2.SetTabLabel (this.table3, this.label76);
		this.label76.ShowAll ();
		this.vbox1.Add (this.notebook2);
		global::Gtk.Box.BoxChild w173 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.notebook2]));
		w173.Position = 1;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.label32.Hide ();
		this.combobox12.Hide ();
		this.combobox11.Hide ();
		this.combobox13.Hide ();
		this.combobox14.Hide ();
		this.treeview1.Hide ();
		this.button7.Hide ();
		this.button8.Hide ();
		this.button6.Hide ();
		this.vbox5.Hide ();
		this.combobox16.Hide ();
		this.combobox17.Hide ();
		this.combobox18.Hide ();
		this.combobox19.Hide ();
		this.treeview2.Hide ();
		this.button9.Hide ();
		this.button10.Hide ();
		this.button11.Hide ();
		this.vbox9.Hide ();
		this.notebook2.Hide ();
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.entry4.Activated += new global::System.EventHandler (this.OnEntry4Activated);
		this.button1.Clicked += new global::System.EventHandler (this.OnButton1Clicked);
		this.combobox1.Changed += new global::System.EventHandler (this.OnCombobox1Changed);
		this.entry3.Activated += new global::System.EventHandler (this.OnEntry3Activated);
		this.combobox3.Changed += new global::System.EventHandler (this.OnCombobox3Changed);
		this.combobox4.Changed += new global::System.EventHandler (this.OnCombobox4Changed);
		this.combobox5.Changed += new global::System.EventHandler (this.OnCombobox5Changed);
		this.combobox6.Changed += new global::System.EventHandler (this.OnCombobox6Changed);
		this.combobox7.Changed += new global::System.EventHandler (this.OnCombobox7Changed);
		this.button4.Clicked += new global::System.EventHandler (this.OnButton4Clicked);
		this.checkbutton4.Toggled += new global::System.EventHandler (this.OnCheckbutton4Toggled);
		this.checkbutton5.Toggled += new global::System.EventHandler (this.OnCheckbutton5Toggled);
		this.button3.Clicked += new global::System.EventHandler (this.OnButton3Clicked);
		this.entry5.Activated += new global::System.EventHandler (this.OnEntry5Activated);
		this.entry6.Activated += new global::System.EventHandler (this.OnEntry6Activated);
		this.combobox9.Changed += new global::System.EventHandler (this.OnCombobox9Changed);
		this.button5.Clicked += new global::System.EventHandler (this.OnButton5Clicked);
		this.entry7.Activated += new global::System.EventHandler (this.OnEntry7Activated);
		this.checkbutton7.Clicked += new global::System.EventHandler (this.OnCheckbutton7Clicked);
		this.checkbutton8.Clicked += new global::System.EventHandler (this.OnCheckbutton8Clicked);
		this.combobox10.Changed += new global::System.EventHandler (this.OnCombobox10Changed);
		this.combobox12.Changed += new global::System.EventHandler (this.OnCombobox12Changed);
		this.combobox11.Changed += new global::System.EventHandler (this.OnCombobox11Changed);
		this.combobox13.Changed += new global::System.EventHandler (this.OnCombobox13Changed);
		this.combobox14.Changed += new global::System.EventHandler (this.OnCombobox14Changed);
		this.treeview1.CursorChanged += new global::System.EventHandler (this.OnTreeview1CursorChanged);
		this.button7.Clicked += new global::System.EventHandler (this.OnButton7Clicked);
		this.button8.Clicked += new global::System.EventHandler (this.OnButton8Clicked);
		this.button6.Clicked += new global::System.EventHandler (this.OnButton6Clicked);
		this.button12.Clicked += new global::System.EventHandler (this.OnButton12Clicked);
		this.entry8.Activated += new global::System.EventHandler (this.OnEntry8Activated);
		this.checkbutton9.Clicked += new global::System.EventHandler (this.OnCheckbutton9Clicked);
		this.checkbutton10.Clicked += new global::System.EventHandler (this.OnCheckbutton10Clicked);
		this.combobox15.Changed += new global::System.EventHandler (this.OnCombobox15Changed);
		this.combobox16.Changed += new global::System.EventHandler (this.OnCombobox16Changed);
		this.combobox17.Changed += new global::System.EventHandler (this.OnCombobox17Changed);
		this.combobox18.Changed += new global::System.EventHandler (this.OnCombobox18Changed);
		this.combobox19.Changed += new global::System.EventHandler (this.OnCombobox19Changed);
		this.treeview2.CursorChanged += new global::System.EventHandler (this.OnTreeview2CursorChanged);
		this.button9.Clicked += new global::System.EventHandler (this.OnButton9Clicked);
		this.button10.Clicked += new global::System.EventHandler (this.OnButton10Clicked);
		this.button11.Clicked += new global::System.EventHandler (this.OnButton11Clicked);
	}
}
